apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jobfit-pipeline-workspace
  namespace: jobfit
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
