apiVersion: v1
kind: Service
metadata:
  name: openserp
  namespace: openserp
  labels:
    app.kubernetes.io/name: openserp
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: openserp
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: openserp
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
