apiVersion: v1
kind: Service
metadata:
  name: jobfit-web
  namespace: jobfit
spec:
  type: NodePort
  selector:
    app: jobfit-web
  ports:
    - port: 7860
      targetPort: 7860
      nodePort: 30786
